name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  message:
    description: 'Message to print'
    default: 'Hello World!'
  count:
    description: "Number of times to print"
    default: 10
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
    - ${{ inputs.count }}
